name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and Test
    if: ${{ github.ref == 'refs/heads/develop' }}
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: develop
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.1.0

      - name: Determine Version with GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4.1.0

      - name: Validate Tag
        id: validate
        run: |
          TAG=v${{ steps.gitversion.outputs.majorMinorPatch }}
          echo "Checking if tag $TAG exists on origin..."
          if git ls-remote --tags origin "refs/tags/$TAG" | grep -q "$TAG"; then
            echo "Tag exists"
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag does not exist"
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Tag already exists, abort
        if: ${{ steps.validate.outputs.tag_exists == 'true' }}
        run: |
          echo "Tag v${{ steps.gitversion.outputs.majorMinorPatch }} already exists. Skipping release."
          exit 0


      - name: Merge to main
        if: ${{ steps.validate.outputs.tag_exists != 'true' }}
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff develop -m "Release v${{ steps.gitversion.outputs.majorMinorPatch }}"
          git push origin main

      - name: Create Git tag
        if: ${{ steps.validate.outputs.tag_exists != 'true' }}
        run: |
          git tag -a v${{ steps.gitversion.outputs.majorMinorPatch }} -m "Release v${{ steps.gitversion.outputs.majorMinorPatch }}"
          git push origin v${{ steps.gitversion.outputs.majorMinorPatch }}

      - name: Merge back to develop
        if: ${{ steps.validate.outputs.tag_exists != 'true' }}
        run: |
          git checkout develop
          git pull origin develop
          git merge --no-ff main -m "Merge main back to develop after release v${{ steps.gitversion.outputs.majorMinorPatch }}"
          git push origin develop
